# SPDX-License-Identifier: GPL-2.0-only
snd-soc-xuantie-th1520-i2s-objs := th1520-i2s-common.o \
				       th1520-pcm-dma.o \
				       th1520-i2s.o
obj-$(CONFIG_SND_SOC_XUANTIE_TH1520_I2S) += snd-soc-xuantie-th1520-i2s.o
obj-$(CONFIG_SND_SOC_XUANTIE_TH1520_HDMI_PCM) += th1520-hdmi-pcm.o
